In [1]:
import pandas as pd

In [3]:
print(pd.__version__)

3.0.6

In [8]:
# arrar 1d
serie=pd.Series(
    [1,2,3,4,5],
    index=['a','b','c','d','e'],
    name='mi_serie',
    )

# Arrar 2d
df=pd.DataFrame({
'producto': ['A','B','C','D'],
'precio': [100,200,300,400],
})

In [9]:
df

  producto  precio
0        A     100
1        B     200
2        C     300
3        D     400

In [13]:
serie_ventas=pd.Series(
    [100,200,300,400],
    index=['Enero','Febrero','Marzo','Abril'],
    name='ventas',
)
print(serie_ventas)
print(serie_ventas.mean())

Enero      100
Febrero    200
Marzo      300
Abril      400
Name: ventas, dtype: int64
250.0

##  Data frames
### Crear Dataframes desde un diccionario

In [16]:
df=pd.DataFrame({
    'producto': ['Laptop','Monitor','Teclado','Mouse'],
    'unidades': [10,20,30,40],
    'precio': [100,200,300,400],
})

In [15]:
print(df)

  producto  unidades  precio
0        A        10     100
1        B        20     200
2        C        30     300
3        D        40     400

### dESDE UNA LISTA DE DICCIONARIOS

In [18]:
### dESDE UNA LISTA DE DICCIONARIOS
df2=pd.DataFrame([
    {'producto': 'Laptop', 'unidades': 10, 'precio': 100},
    {'producto': 'Monitor', 'unidades': 20, 'precio': 200},
    {'producto': 'Teclado', 'unidades': 30, 'precio': 300},
    {'producto': 'Mouse', 'unidades': 40, 'precio': 400}
])

In [19]:
print(df2)

  producto  unidades  precio
0   Laptop        10     100
1  Monitor        20     200
2  Teclado        30     300
3    Mouse        40     400

### Desde una lista de listas

In [20]:
df3=pd.DataFrame(
    [
    ['Laptop', 10, 100],
    ['Monitor', 20, 200],
    ['Teclado', 30, 300],
    ['Mouse', 40, 400]
], 
columns=['producto', 'unidades', 'precio']
)
df3

  producto  unidades  precio
0   Laptop        10     100
1  Monitor        20     200
2  Teclado        30     300
3    Mouse        40     400

### Operaciones

In [29]:
# Columnas calculadas
df3['Inv_Valorizado'] = df3['unidades'] * df3['precio']
print(df3)
df3.shape
print(df3.columns.to_list())
print(df3.describe())

  producto  unidades  precio  total  Inv_Valorizado
0   Laptop        10     100   1000            1000
1  Monitor        20     200   4000            4000
2  Teclado        30     300   9000            9000
3    Mouse        40     400  16000           16000
['producto', 'unidades', 'precio', 'total', 'Inv_Valorizado']
        unidades      precio         total  Inv_Valorizado
count   4.000000    4.000000      4.000000        4.000000
mean   25.000000  250.000000   7500.000000     7500.000000
std    12.909944  129.099445   6557.438524     6557.438524
min    10.000000  100.000000   1000.000000     1000.000000
25%    17.500000  175.000000   3250.000000     3250.000000
50%    25.000000  250.000000   6500.000000     6500.000000
75%    32.500000  325.000000  10750.000000    10750.000000
max    40.000000  400.000000  16000.000000    16000.000000